# Generated by Django 5.1.15 on 2026-04-26 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV', 'Csv')], max_length=16)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mentor',
                'verbose_name_plural': 'mentores',
                'db_table': 'mentores_mentor',
                'indexes': [models.Index(fields=['activo'], name='mentores_me_activo_ae78f9_idx')],
            },
        ),
    ]
