# Generated by Django 5.1.15 on 2026-04-26 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorPeriodo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(db_index=True, max_length=20)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV', 'Csv')], max_length=16)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha_alta', models.DateTimeField()),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('desactivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'periodo de mentor',
                'verbose_name_plural': 'periodos de mentor',
                'db_table': 'mentores_mentorperiodo',
                'ordering': ['-fecha_alta'],
                'indexes': [models.Index(fields=['matricula', 'fecha_baja'], name='mentores_me_matricu_f3695e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_baja__isnull', True)), fields=('matricula',), name='unique_active_period_per_matricula')],
            },
        ),
    ]
