# Generated by Django 5.1.15 on 2026-04-25 20:37

import usuarios.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente'), ('CONTROL_ESCOLAR', 'Control Escolar'), ('RESPONSABLE_PROGRAMA', 'Responsable Programa'), ('ADMIN', 'Admin')], max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios_user',
            },
            managers=[
                ('objects', usuarios.models.user.UserManager()),
            ],
        ),
    ]
