# Generated by Django 5.1.15 on 2026-04-25 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('responsible_role', models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente'), ('CONTROL_ESCOLAR', 'Control Escolar'), ('RESPONSABLE_PROGRAMA', 'Responsable Programa'), ('ADMIN', 'Admin')], max_length=32)),
                ('creator_roles', models.JSONField(default=list)),
                ('requires_payment', models.BooleanField(default=False)),
                ('mentor_exempt', models.BooleanField(default=False)),
                ('plantilla_id', models.UUIDField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de solicitud',
                'verbose_name_plural': 'tipos de solicitud',
                'db_table': 'solicitudes_tiposolicitud',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'responsible_role'], name='solicitudes_activo_a96e5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('SELECT', 'Select'), ('FILE', 'File')], max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('accepted_extensions', models.JSONField(blank=True, default=list)),
                ('max_size_mb', models.PositiveIntegerField(default=10)),
                ('max_chars', models.PositiveIntegerField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='solicitudes.tiposolicitud')),
            ],
            options={
                'verbose_name': 'campo de tipo de solicitud',
                'verbose_name_plural': 'campos de tipo de solicitud',
                'db_table': 'solicitudes_fielddefinition',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'order'), name='unique_field_order_per_tipo')],
            },
        ),
    ]
