# Generated by Django 5.1.15 on 2026-04-26 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'contador de folio',
                'verbose_name_plural': 'contadores de folio',
                'db_table': 'solicitudes_foliocounter',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=16)),
                ('form_snapshot', models.JSONField()),
                ('valores', models.JSONField(default=dict)),
                ('requiere_pago', models.BooleanField()),
                ('pago_exento', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.tiposolicitud')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'db_table': 'solicitudes_solicitud',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=16, null=True)),
                ('estado_nuevo', models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=16)),
                ('actor_role', models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente'), ('CONTROL_ESCOLAR', 'Control Escolar'), ('RESPONSABLE_PROGRAMA', 'Responsable Programa'), ('ADMIN', 'Admin')], max_length=32)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'entrada de historial',
                'verbose_name_plural': 'historial de estados',
                'db_table': 'solicitudes_historialestado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['solicitante', '-created_at'], name='solicitudes_solicit_8883a4_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', '-created_at'], name='solicitudes_estado_3e4731_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['tipo', 'estado'], name='solicitudes_tipo_id_24d982_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestado',
            index=models.Index(fields=['solicitud', '-created_at'], name='solicitudes_solicit_64665d_idx'),
        ),
    ]
