# Generated by Django 5.1.15 on 2026-04-26 04:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_foliocounter_solicitud_historialestado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposolicitud',
            name='plantilla_id',
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=16),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=16),
        ),
        migrations.CreateModel(
            name='PlantillaSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('html', models.TextField()),
                ('css', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plantilla de solicitud',
                'verbose_name_plural': 'plantillas de solicitud',
                'db_table': 'solicitudes_plantillasolicitud',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'nombre'], name='solicitudes_activo_c6141e_idx')],
            },
        ),
        migrations.AddField(
            model_name='tiposolicitud',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos', to='solicitudes.plantillasolicitud'),
        ),
    ]
