# Generated by Django 5.1.15 on 2026-05-16 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_fielddefinition_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente'), ('CONTROL_ESCOLAR', 'Control Escolar'), ('RESPONSABLE_PROGRAMA', 'Responsable Programa'), ('ADMIN', 'Admin')], max_length=32)),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'respuesta de solicitud',
                'verbose_name_plural': 'respuestas de solicitud',
                'db_table': 'solicitudes_respuestasolicitud',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='solicitudes.respuestasolicitud')),
            ],
            options={
                'verbose_name': 'archivo de respuesta',
                'verbose_name_plural': 'archivos de respuesta',
                'db_table': 'solicitudes_archivorespuesta',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='respuestasolicitud',
            index=models.Index(fields=['solicitud', 'created_at'], name='solicitudes_solicit_f9edd1_idx'),
        ),
        migrations.AddIndex(
            model_name='archivorespuesta',
            index=models.Index(fields=['respuesta', 'created_at'], name='solicitudes_respues_429b96_idx'),
        ),
    ]
