# Generated by Django 5.1.15 on 2026-05-17 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_respuestasolicitud_archivorespuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('plantilla', 'Por plantilla')], max_length=10)),
                ('imagen', models.FileField(upload_to='plantilla_assets/%Y/%m/')),
                ('mime_type', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='solicitudes.plantillasolicitud')),
            ],
            options={
                'verbose_name': 'asset de plantilla',
                'verbose_name_plural': 'assets de plantillas',
                'db_table': 'solicitudes_plantillaasset',
                'ordering': ['scope', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('slug',), name='unique_global_asset_slug'), models.UniqueConstraint(condition=models.Q(('scope', 'plantilla')), fields=('plantilla', 'slug'), name='unique_plantilla_asset_slug'), models.CheckConstraint(condition=models.Q(models.Q(('plantilla__isnull', True), ('scope', 'global')), models.Q(('plantilla__isnull', False), ('scope', 'plantilla')), _connector='OR'), name='plantilla_asset_scope_consistency')],
            },
        ),
    ]
